FROM ubuntu:24.04

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
      openssl curl wget git build-essential cmake ninja-build pkg-config \
      libx11-dev libxext-dev libxrandr-dev libxrender-dev libxfixes-dev libvorbisfile3 libopusfile-dev \
      libxi-dev libxinerama-dev libxcursor-dev libwayland-dev libxkbcommon-dev wayland-protocols \
      libgl1-mesa-dev qt6-base-dev libasound2-dev qt6-xdgdesktopportal-platformtheme ; \
    apt-get clean

RUN mkdir /workspace
VOLUME /workspace
WORKDIR /workspace
